### PR TITLE
Support tokens in client initialisation

### PR DESCRIPTION
**Pull request by bobjflong**

### CODE REVIEW

**Comment by RuairiK** [comment]
:+1:

**Comment by vhmth** [comment]
:+1: any hold up on this getting in? Trying this out locally by essentially just passing the OAuth token as the `appId` and then in the lib overriding the `appApiKey` to be an empty string (just for testing purposes). I'm getting a `token_unauthorized` error, but I don't think it's `unirest` setting things incorrectly because when I decode the basic auth header it's of the correct form "TOKEN:".

For posterity's sake:

[Error: {"statusCode":401,"body":{"type":"error.list","request_id":"7307accd-301f-4319-b728-123476dc9288","errors":[{"code":"token_unauthorized","message":"Not authorized to access resource"}]},"headers":{"cache-control":"no-cache","content-type":"application/json; charset=utf-8","date":"Thu, 31 Mar 2016 02:18:26 GMT","server":"nginx","status":"401 Unauthorized","strict-transport-security":"max-age=31557600; includeSubDomains; preload","vary":"Accept-Encoding","www-authenticate":"Basic realm=\"intercom.io\"","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-intercom-version":"8593f6827196a860e79f0110207d3ad05883c370","x-ratelimit-limit":"500","x-ratelimit-remaining":"500","x-ratelimit-reset":"1459390740","x-request-id":"7307accd-301f-4319-b728-123476dc9288","x-runtime":"0.029250","x-xss-protection":"1; mode=block","transfer-encoding":"chunked","connection":"Close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.intercom.io","port":443,"hostname":"api.intercom.io","hash":null,"search":null,"query":null,"pathname":"/users","path":"/users","href":"https://api.intercom.io/users"},"method":"get","headers":{"Content-Type":"application/json","Accept":"application/json","User-Agent":"intercom-node-client/2.0.0","authorization":"Basic <BASE_64_OF_token:>","content-length":0}}}]

**Comment by vhmth** [comment]
Ok just realized I don't have access to the users list from my application's OAuth. It seems to be working with the hack above (single-space `appApiKey` to pass the constructor check and then the token as the `app_id`).

**Comment by bobjflong** [comment]
Released as `2.8.0`!

**Comment by vhmth** [comment]
iron_man_boom

**Pull request merged**
