### PR TITLE
Add ability to change intercom base url, for testing purposes

### PR DESCRIPTION
**Pull request by nadav-dav**
Basically a simple change, to make the client more testable. (For example, work against a stub server).

### CODE REVIEW

**Comment by Skaelv** [comment]
looks good. @nadav-dav Thanks for your contribution!

**Comment by nadav-dav** [comment]
Hey @Skaelv ! :D Can you publish this? I really need to use this

**Comment by Skaelv** [comment]
Just did :)

**Comment by nadav-dav** [comment]
That's true love right there!

**Pull request merged**
