### PR TITLE
Support for permanently delete a user

### LINKED ISSUE #194: Add support for user deletion
Docs:  https://developers.intercom.com/v2.0/reference#delete-users

### PR DESCRIPTION
**Pull request by rhodgkins**
Closes #194.

Change summary:

* Renamed `users.delete` to `users.archive`
* Deprecated old `users.delete`
* Added tests for permanently deleting a user
* Implemented permanent user deletion
* Update docs

### CODE REVIEW

**Comment by vhmth** [comment]
Woo! Am I able to review or does it have to be an official Intercom peep?

**Comment by Rynoh** [comment]
@rhodgkins Hi, any idea how long its going to be before this is merged?

**Comment by Sh33pman** [comment]
@choran Can we give us a timeline on this please?

**Comment by ffxsam** [comment]
Hopefully someone can officially get archive & delete functions in here.

**Comment by choran** [comment]
@rhodgkins et all .. first of all sorry for the radio silence here. 
I have been meaning to get to these, I have focused on GDPR issues for the API and I just didnt get a chance to get to these. We are trying to address this so that in future so SDK PRs and changes are dealt with far more quickly, especially when community members take the time and effort to make these changes.
It is much appreciated and it is something we need to make sure we react to more quickly.

I will try and get to this next week and merge it. I think the way you have dealt with it makes sense.
It is a breaking change in removing delete but I dont think there is any other way we can address that. 
I just want to take a look at the other SDKs to make sure we are making consistent changes across the board.
Thanks again

Cathal

**Comment by rhodgkins** [comment]
@choran No problem!

Just to add:

>It is a breaking change in removing delete

It's still there but will produce [console warnings](https://nodejs.org/docs/latest-v6.x/api/util.html#util_util_deprecate_function_string) when used. I guess it can be removed as a breaking change once you guys decide to release v3 (or v2.10)!

**Comment by choran** [comment]
@rhodgkins  ah .. I didnt see that. That is pretty cool, node is not my primary language so was not aware of that feature. The PR looks good and given the comments here I will merge this and publish ASAP
Thanks again for this

**Pull request merged**
