### PR TITLE
Allow delete user by user_id or email

### PR DESCRIPTION
**Pull request by idris**
As documented: https://doc.intercom.io/api/#delete-a-user

### CODE REVIEW

**Comment by idris** [comment]
@bobjflong what's the process to get this merged?

**Comment by bobjflong** [comment]
Hey @idris sorry for the delay. Happy to merge this once there's a spec. Would you be up for adding that?

**Comment by idris** [comment]
@bobjflong done!

**Comment by bobjflong** [comment]
thanks!

**Comment by bobjflong** [comment]
released in `2.5.0`

**Pull request merged**
