### PR TITLE
Upgrade gulp nsp

### PR DESCRIPTION
**Pull request by tejasmanohar**
This solves the build error seen on `master` if you re-run Travis CI (or `npm test` after a fresh `npm install`, clean node_modules and whatnot before if you want to test locally). It also solves the problem troubling #54 ( @bsiddiqui you will need to merge master to your branch once this PR is merged )

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Oh, hm... tests still failing what. Not locally O.o - lemme see.

**Comment by bsiddiqui** [comment]
@tejasmanohar yup same with my branch without this change - I tried the change you have in this PR but didn't have time to dig deeper

**Comment by tejasmanohar** [comment]
@bsiddiqui Yeah, just for an update, I have to knock out some other work but will also revisit this in the evening :)

**Comment by tejasmanohar** [comment]
@bsiddiqui Ok, took a look again. Was a very simple issue- not sure why the 'admin' test failed the first time on Travis... but the issue that was actually relevant was _path#join_ vs concatenating directories since the latter doesn't work all the time on Windows (*ew*).

Anyways, once this PR is merged- just merge changes down to your branch :+1: // cc @bobjflong

**Comment by bobjflong** [comment]
Merging this - looking at https://github.com/intercom/intercom-node/pull/54

**Pull request merged**
