### PR TITLE
Add email parameter to contacts.update

### PR DESCRIPTION
**Pull request by i-tu**
See https://github.com/intercom/intercom-node/issues/313

### CODE REVIEW

**Review by johnnynader — APPROVED** [review]
Thank you for that!

**Comment by wmadden** [comment]
When will this be released?

**Comment by i-tu** [comment]
Any information about a release timeline @johnnynader ?

**Comment by i-tu** [comment]
It's been three months and I'm getting desperate. Trying to get some attention to this PR by tagging active contributors.

@johnnynader @hypeofpipe @enrico-intercom @SeanHealy33

**Comment by johnnynader** [comment]
v3.1.5 is now out with the fix

**Pull request closed without merging**
