### PR TITLE
Add stable node

### PR DESCRIPTION
**Pull request by danielhusar**
Add stable node instead of hardcoding 4.

### CODE REVIEW

**Comment by danielhusar** [comment]
@bobjflong ^

**Comment by bobjflong** [comment]
:+1:

**Comment by tejasmanohar** [comment]
You should do both. 4.x.x is LTS so you wanna run tests on that :)

**Comment by danielhusar** [comment]
Its not really necessary and most people dont do it.

**Comment by tejasmanohar** [comment]
This is the first time we've had LTS node :) - but whatever, I doubt you'll run into a failure because of it in this case since a) transpiling b) not using many likely to change system APIs (like `worker`) so not going to bother arguing :)

**Pull request merged**
