### PR TITLE
Use default exports for clarity

### PR DESCRIPTION
**Pull request by tejasmanohar**

### CODE REVIEW

**Comment by tejasmanohar** [comment]
@bobjflong So something weird's going on here- pretty sure it's with your build script through Gulp? I replaced `babel()` w/ `babel({stage: 1})` in the Gulpfile locally and tested and same issue. As you can see, usage works, tests pass, precompiling works, but one of the gulp tasks is throwing a syntax error when transpiling (though there seemingly is none)...

**Comment by tejasmanohar** [comment]
Aha, tests should pass after 8f05214. Didn't notice you guys didn't have [babel-eslint](https://github.com/babel/babel-eslint) parser included....that's needed for all the ES6/7 stuff that isn't in ESLint yet :wink:

**Comment by bobjflong** [comment]
Unfortunately today's changes has caused some conflicts on these PRs. I may get time to help resolve them

**Comment by tejasmanohar** [comment]
Solved the merge conflicts, @bobjflong

**Comment by bobjflong** [comment]
:+1:

**Pull request merged**
