### PR TITLE
chore: demote sinon to dev dependencies

### PR DESCRIPTION
**Pull request by vkarpov15**
Sinon doesn't need to be a prod dependency, the only place you use it is here: https://github.com/intercom/intercom-node/blob/4bd04979a0a0ba962d0f396fba9bf4c39f2ebefd/test/user-data.js

### CODE REVIEW

**Comment by jpike88** [comment]
I really would prefer installation without this donation message too.

screen shot 2018-07-26 at 1 59 48 pm

https://github.com/sinonjs/sinon/issues/1737

**Comment by jpike88** [comment]
@jonnyom this is such a minor, fast pr to accept. Can you please just let it through?

**Comment by jpike88** [comment]
@vkarpov15 actually could you amend this PR to an updated version of sinon? They deleted that annoying as hell donation message, it's incredibly grating to see that love heart appearing in all my build logs.

**Comment by vkarpov15** [comment]
@jonnyom done.

**Comment by jpike88** [comment]
@jonnyom just confirming that the donation message issue is fixed

**Comment by jpike88** [comment]
@jonnyom whats our ETA on approving this? I'm getting triggered constantly in my build logs

**Comment by jonnyom** [comment]
@jpike88 - we identified an issue with CI not building forked repos, which is where the delay came from here. We should have this updated and released to a new version by next week.

Thanks for the patience on this one.

**Pull request merged**
